import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#4e7fff',
  },
  screen: {
    flex: 1,
    backgroundColor: '#f8f9fb',
  },
  hero: {
    backgroundColor: '#4e7fff',
    paddingTop: 18,
    paddingBottom: 24,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
    overflow: 'hidden',
  },
  // decorative circles removed
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerRight: {
    padding: 8,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.2)',
    marginRight: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.25)',
  },
  avatarImage: {
    width: 26,
    height: 26,
    resizeMode: 'contain',
  },
  greetSmall: {
    color: 'rgba(255,255,255,0.9)',
    fontSize: 12,
  },
  greetLarge: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 0.2,
    marginTop: 2,
  },
  searchBar: {
    marginTop: 16,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 12,
    paddingHorizontal: 12,
    height: 42,
  },
  searchInput: {
    flex: 1,
    marginHorizontal: 8,
    color: '#202124',
    paddingVertical: 0,
  },
  content: {
    flex: 1,
  },
  contentContainer: {
    paddingVertical: 18,
  },
  promoRow: {
    paddingHorizontal: 16,
  },
  promoCard: {
    width: 240,
    borderRadius: 16,
    padding: 16,
    marginRight: 12,
    backgroundColor: '#E8F0FE',
  },
  promoBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#4e7fff',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    marginBottom: 8,
  },
  promoBadgeText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '700',
  },
  promoTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111',
  },
  promoSubtitle: {
    marginTop: 4,
    color: '#5f6368',
    fontSize: 13,
  },
  promoBottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 14,
  },
  promoAvatar: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
    borderWidth: 1,
    borderColor: '#dfe1e6',
  },
  promoMeta: {
    color: '#4e7fff',
    fontSize: 12,
    fontWeight: '700',
  },
  sectionHeader: {
    marginTop: 18,
    marginBottom: 8,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#202124',
  },
  sectionAction: {
    fontSize: 12,
    color: '#4e7fff',
    fontWeight: '700',
  },
  quickGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 10,
  },
  quickItem: {
    width: '25%',
    alignItems: 'center',
    marginBottom: 16,
  },
  quickIconWrap: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#eef3ff',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#e3e9ff',
    marginBottom: 6,
  },
  quickLabel: {
    fontSize: 12,
    color: '#202124',
    fontWeight: '600',
  },
  cardRow: {
    paddingLeft: 16,
    paddingRight: 4,
  },
  card: {
    width: 240,
    borderRadius: 14,
    backgroundColor: '#fff',
    marginRight: 12,
  },
  cardImage: {
    height: 120,
    backgroundColor: '#eef3ff',
    borderTopLeftRadius: 14,
    borderTopRightRadius: 14,
    overflow: 'hidden',
  },
  cardImageImg: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  cardChip: {
    position: 'absolute',
    left: 10,
    top: 10,
    backgroundColor: '#111827',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  cardChipText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '700',
  },
  cardBody: {
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  cardTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#111',
    marginBottom: 6,
  },
  cardMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  cardMetaText: {
    marginLeft: 4,
    color: '#5f6368',
    fontSize: 12,
    marginRight: 8,
  },
  dot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#d0d5dc',
    marginRight: 8,
  },
  dogRow: {
    paddingHorizontal: 16,
    flexDirection: 'row',
    marginBottom: 16,
  },
  dogCard: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 12,
    marginRight: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  dogAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
    borderWidth: 1,
  },
  dogAvatarBlue: {
    backgroundColor: '#e9f1ff',
    borderColor: '#cfe0ff',
  },
  dogAvatarPink: {
    backgroundColor: '#ffe9f3',
    borderColor: '#ffd0e6',
  },
  dogInfo: {
    flex: 1,
  },
  dogName: {
    fontSize: 14,
    fontWeight: '700',
    color: '#111',
  },
  dogSub: {
    fontSize: 12,
    color: '#5f6368',
    marginTop: 2,
  },
  spacerLarge: {
    height: 28,
  },
  tabbar: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 16,
    backgroundColor: '#ffffff',
    borderRadius: 18,
    height: 70,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 6,
    borderWidth: 1,
    borderColor: '#eef0f5',
  },

  tabItem: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    marginBottom: -50,
  },

  tabItemCenter: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: -40,
  },

  tabFab: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#4e7fff',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#4e7fff',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 6,
  },


  tabLabel: {
    fontSize: 11,
    color: '#9aa0a6',
    marginTop: 4,
    fontWeight: '600',
  },
  tabLabelActive: {
    fontSize: 11,
    color: '#4e7fff',
    marginTop: 4,
    fontWeight: '700',
  },

  circleBtn: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#4e7fff",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 120,
  }
});


