import { StyleSheet } from "react-native";

export default StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: "#fff",
    },
    postHeader: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 12,
    },
    postUser: {
        fontSize: 16,
        fontWeight: "600",
        color: "#111",
    },
    postTime: {
        fontSize: 12,
        color: "#888",
        marginTop: 2,
    },
    postTitle: {
        fontSize: 18,
        fontWeight: "700",
        color: "#222",
        marginBottom: 8,
    },
    postImage: {
        width: "100%",
        height: 200,
        borderRadius: 8,
        marginBottom: 12,
    },
    postContent: {
        fontSize: 15,
        lineHeight: 22,
        color: "#333",
        marginBottom: 16,
    },
    commentSection: {
        marginTop: 10,
        borderTopWidth: 1,
        borderTopColor: "#eee",
        paddingTop: 12,
    },
    commentTitle: {
        fontSize: 16,
        fontWeight: "600",
        marginBottom: 10,
    },
    commentItem: {
        marginBottom: 16,
        paddingBottom: 12,
        borderBottomWidth: 1,
        borderBottomColor: "#f0f0f0",
    },
    commentAuthor: {
        fontSize: 14,
        fontWeight: "600",
        color: "#222",
    },
    commentText: {
        fontSize: 14,
        color: "#333",
        marginTop: 4,
        marginBottom: 4,
    },
    commentTime: {
        fontSize: 12,
        color: "#888",
    },
    replyButton: {
        fontSize: 12,
        color: "#4e7fff",
        marginTop: 6,
    },
    replyItem: {
        flexDirection: "row",
        alignItems: "flex-start",
        marginTop: 6,
        paddingLeft: 10,
        borderLeftWidth: 2,
        borderLeftColor: "#ddd",
    },
    replyAuthor: {
        fontSize: 13,
        fontWeight: "600",
        color: "#222",
    },
    replyText: {
        fontSize: 13,
        color: "#444",
        marginTop: 2,
        marginBottom: 2,
    },
    replyTime: {
        fontSize: 11,
        color: "#999",
    },
    commentInputRow: {
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 8,
        borderTopWidth: 1,
        borderTopColor: "#eee",
        backgroundColor: "#fff",
    },
    commentInput: {
        flex: 1,
        borderWidth: 1,
        borderColor: "#ccc",
        borderRadius: 20,
        paddingHorizontal: 14,
        paddingVertical: 8,
        fontSize: 14,
        backgroundColor: "#fafafa",
    },
    commentButton: {
        marginLeft: 8,
        backgroundColor: "#4e7fff",
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 20,
    },
    commentButtonText: {
        color: "#fff",
        fontSize: 14,
        fontWeight: "600",
    },
    replyInputRow: {
        flexDirection: "row",
        alignItems: "center",
        marginTop: 8,
        marginLeft: 24,
    },
    replyInput: {
        flex: 1,
        borderWidth: 1,
        borderColor: "#ccc",
        borderRadius: 20,
        paddingHorizontal: 12,
        paddingVertical: 6,
        fontSize: 13,
        backgroundColor: "#fafafa",
    },
    replyButtonSubmit: {
        marginLeft: 6,
        backgroundColor: "#4e7fff",
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 16,
    },
    replyButtonText: {
        color: "#fff",
        fontSize: 12,
        fontWeight: "600",
    },
    modalOverlay: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "rgba(0,0,0,0.5)",
    },
    modalBox: {
        width: "80%",
        backgroundColor: "#fff",
        borderRadius: 12,
        padding: 20,
        alignItems: "center",
    },
    modalTitle: {
        fontSize: 16,
        fontWeight: "600",
        marginBottom: 12,
    },
    modalInput: {
        width: "100%",
        borderWidth: 1,
        borderColor: "#ccc",
        borderRadius: 8,
        padding: 10,
        fontSize: 14,
        marginBottom: 12,
    },
    modalButton: {
        flex: 1,
        paddingVertical: 10,
        borderRadius: 8,
        alignItems: "center",
    },
    modalButtonText: {
        fontSize: 14,
        fontWeight: "600",
        color: "#fff",
    },
    toggleReplies: {
        fontSize: 12,
        color: "#4e7fff",
        marginTop: 6,
        marginLeft: 24,
    },
    likeRow: {
        flexDirection: "row",
        alignItems: "center",
        marginVertical: 10,
    },
    likeButton: {
        flexDirection: "row",
        alignItems: "center",
    },
    likeCount: {
        marginLeft: 6,
        fontSize: 14,
        color: "#333",
    },

});
